apiVersion: 1
groups:
    - orgId: 1
      name: 1m
      folder: "1"
      interval: 10s
      rules:
        - uid: dffd0774-3938-42f5-ae33-2ba78d6bb167
          title: NGINX Log Exporter Utilization (Response Count)
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: |
                    rate(nginx_http_response_count_total[1m]) * 60
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: max
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: e302bc45-4efe-495d-91a8-43d068022975
          panelId: 13
          noDataState: NoData
          execErrState: Error
          for: 30s
          annotations:
            __dashboardUid__: e302bc45-4efe-495d-91a8-43d068022975
            __panelId__: "13"
            description: nginx count > 60
            summary: nginx count > 60
          isPaused: false
