{
 "title": "Node and Nginx Dashboards",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU_Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"irq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes / node_memory_MemTotal_bytes\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m]) * 100 > 1\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total[1m]) + rate(node_network_transmit_errs_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"irq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks Saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m]) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total[1m]) + rate(node_network_transmit_drop_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_Saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m]) + rate(node_network_transmit_bytes_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}} {{instance}}" },
    { "expr": "node_load5", "legendFormat": "{{__name__}} {{instance}}" },
    { "expr": "node_load15", "legendFormat": "{{__name__}} {{instance}}" },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"}) by (instance)\n",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  {
   "title": "NGINX Log Exporter Utilization (Response Count)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(nginx_http_response_count_total[1m]) * 60\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Log Exporter Saturation (Response Size)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "rate(nginx_http_response_size_bytes[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}